"use client"

import { useCallback, useState } from "react"
import { ChevronDown, Copy, Download } from "lucide-react"

import { cn, formatINR } from "@/lib/utils"
import type { GSTR3BSummary } from "@/lib/reconcile"

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function buildCopyText(period: string, s: GSTR3BSummary): string {
  return [
    `GSTR-3B Table 4A(5) — ${period}`,
    `IGST: ${formatINR(s.eligibleIGST)}`,
    `CGST: ${formatINR(s.eligibleCGST)}`,
    `SGST: ${formatINR(s.eligibleSGST)}`,
    `Total: ${formatINR(s.eligibleTotal)}`,
  ].join("\n")
}

async function openPrintSummary(period: string, s: GSTR3BSummary): Promise<void> {
  const { jsPDF } = await import("jspdf")

  // Fetch Noto Sans as TTF (jsPDF requires TTF, not woff/woff2)
  const fontUrl =
    "https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoSans/hinted/ttf/NotoSans-Regular.ttf"
  const fontBytes = await fetch(fontUrl).then((r) => r.arrayBuffer())

  // Convert ArrayBuffer to base64 in chunks to avoid call stack overflow
  const uint8 = new Uint8Array(fontBytes)
  const chunkSize = 8192
  let binary = ""
  for (let i = 0; i < uint8.length; i += chunkSize) {
    binary += String.fromCharCode(...uint8.subarray(i, i + chunkSize))
  }
  const fontBase64 = btoa(binary)

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })
  doc.addFileToVFS("NotoSans-Regular.ttf", fontBase64)
  doc.addFont("NotoSans-Regular.ttf", "NotoSans", "normal")
  doc.setFont("NotoSans", "normal")

  const navy = [26, 53, 87] as const
  const grey = [100, 116, 139] as const
  const green = [4, 120, 87] as const
  const red = [185, 28, 28] as const
  const amber = [146, 64, 14] as const
  const pageW = 210
  const margin = 20
  const colW = pageW - margin * 2

  let y = 20

  // Header
  doc.setFontSize(16)
  doc.setFont("NotoSans", "normal")
  doc.setTextColor(...navy)
  doc.text(`GSTR-3B ITC Summary — ${period}`, margin, y)
  y += 6
  doc.setFontSize(9)
  doc.setTextColor(...grey)
  doc.text("Generated by GSTRecon · gstrecon.co.in", margin, y)
  y += 10

  const sectionHeader = (title: string, color: readonly [number, number, number]) => {
    doc.setFillColor(240, 245, 255)
    doc.roundedRect(margin, y, colW, 7, 1, 1, "F")
    doc.setFontSize(9)
    doc.setFont("NotoSans", "normal")
    doc.setTextColor(...color)
    doc.text(title, margin + 3, y + 4.8)
    y += 10
  }

  const moneyRow = (label: string, amount: number, bold = false) => {
    doc.setFontSize(9)
    doc.setFont("NotoSans", "normal")
    doc.setTextColor(...navy)
    doc.text(label, margin + 3, y)
    doc.text(formatINR(amount), pageW - margin - 3, y, { align: "right" })
    y += 6
  }

  const moneyRowAmountRgb = (
    label: string,
    amount: number,
    amountRgb: readonly [number, number, number],
  ) => {
    doc.setFontSize(9)
    doc.setFont("NotoSans", "normal")
    doc.setTextColor(...navy)
    doc.text(label, margin + 3, y)
    doc.setTextColor(...amountRgb)
    doc.text(formatINR(amount), pageW - margin - 3, y, { align: "right" })
    doc.setTextColor(...navy)
    y += 6
  }

  const divider = () => {
    doc.setDrawColor(226, 232, 240)
    doc.line(margin, y - 2, pageW - margin, y - 2)
    y += 2
  }

  sectionHeader("✓  Table 4A(5) — Eligible ITC (Matched, ITC available)", green)
  moneyRow("IGST:", s.eligibleIGST)
  moneyRow("CGST:", s.eligibleCGST)
  moneyRow("SGST:", s.eligibleSGST)
  divider()
  moneyRow("Total:", s.eligibleTotal, true)
  y += 4

  sectionHeader("Credit / Debit Note Adjustments", navy)
  moneyRowAmountRgb("Credit Notes (reduce ITC):", s.creditNoteITC ?? 0, red)
  moneyRowAmountRgb("Debit Notes (increase ITC):", s.debitNoteITC ?? 0, green)
  divider()
  moneyRow("Net after notes:", s.netAfterNotes ?? s.netClaimableTotal, true)
  y += 4

  sectionHeader("✗  Table 4D(1) — Ineligible ITC (Sec 17(5) / ITC blocked)", red)
  moneyRow("IGST:", s.ineligibleIGST)
  moneyRow("CGST:", s.ineligibleCGST)
  moneyRow("SGST:", s.ineligibleSGST)
  divider()
  moneyRow("Total:", s.ineligibleTotal, true)
  y += 4

  sectionHeader("⚠  Deferred — Do not claim this month", amber)
  moneyRow("Missing in 2B (PR only):", s.deferredTotal)
  moneyRow("QRMP pending:", s.qrmpTotal)
  divider()
  moneyRow("Total deferred:", s.deferredTotal + s.qrmpTotal, true)
  y += 8

  // Net ITC banner
  doc.setFillColor(239, 246, 255)
  doc.roundedRect(margin, y, colW, 22, 2, 2, "F")
  doc.setDrawColor(37, 99, 235)
  doc.setLineWidth(0.8)
  doc.line(margin, y, margin, y + 22)
  doc.setLineWidth(0.2)
  doc.setFontSize(11)
  doc.setFont("NotoSans", "normal")
  doc.setTextColor(...navy)
  doc.text(`Net ITC for Table 4A(5): ${formatINR(s.netAfterNotes ?? s.netClaimableTotal)}`, margin + 5, y + 8)
  doc.setFontSize(8)
  doc.setTextColor(...grey)
  doc.text(
    `IGST: ${formatINR(s.netClaimableIGST)}   CGST: ${formatINR(s.netClaimableCGST)}   SGST: ${formatINR(s.netClaimableSGST)}`,
    margin + 5,
    y + 15
  )
  y += 30

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(...grey)
  doc.text(
    `GSTRecon · ${new Date().toLocaleDateString("en-IN")} · For CA use only`,
    pageW / 2,
    285,
    { align: "center" }
  )

  doc.save(`GSTR-3B-ITC-${period.replace(/\s+/g, "-")}.pdf`)
}

function MoneyRow({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex justify-between gap-3 text-sm">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-mono tabular-nums text-brand-navy">{formatINR(value)}</span>
    </div>
  )
}

export function GSTR3BSummary({ summary: s, period }: { summary: GSTR3BSummary; period: string }) {
  const [open, setOpen] = useState(false)
  const [copied, setCopied] = useState(false)

  const totalDeferred = s.deferredTotal + s.qrmpTotal

  const onCopy = useCallback(async () => {
    const text = buildCopyText(period, s)
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      // ignore
    }
  }, [period, s])

  const onDownloadPdf = useCallback(() => {
    void openPrintSummary(period, s)
  }, [period, s])

  return (
    <div className="space-y-2">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex min-h-11 w-full items-center justify-between rounded-xl border border-border bg-white px-4 py-3 text-left shadow-sm transition-colors hover:bg-slate-50"
      >
        <span className="text-[15px] font-semibold text-brand-navy">GSTR-3B ITC Summary</span>
        <ChevronDown
          className={cn("h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200", open && "rotate-180")}
          aria-hidden
        />
      </button>

      {open ? (
        <div className="rounded-xl border border-border bg-white px-5 py-5 shadow-sm sm:px-6 sm:py-6">
          <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <h3 className="text-base font-semibold text-brand-navy">GSTR-3B ITC Entry for {period}</h3>
            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => void onCopy()}
                className={cn(
                  "inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium shadow-sm",
                  copied
                    ? "border-emerald-200 bg-emerald-50 text-emerald-800"
                    : "border-border bg-white text-brand-navy hover:bg-slate-50",
                )}
              >
                <Copy className="h-3.5 w-3.5" aria-hidden />
                {copied ? "✓ Copied!" : "Copy All"}
              </button>
              <button
                type="button"
                onClick={onDownloadPdf}
                className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-white px-3 py-1.5 text-xs font-medium text-brand-navy shadow-sm hover:bg-slate-50"
              >
                <Download className="h-3.5 w-3.5" aria-hidden />
                Download PDF
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            <div className="flex flex-col rounded-lg border border-border">
              <div className="space-y-2 border-b border-border p-4">
                <p className="text-[13px] font-semibold text-emerald-700">✓ Claim in Table 4A(5)</p>
                <MoneyRow label="IGST:" value={s.eligibleIGST} />
                <MoneyRow label="CGST:" value={s.eligibleCGST} />
                <MoneyRow label="SGST:" value={s.eligibleSGST} />
                <div className="my-2 border-t border-border" />
                <div className="flex justify-between gap-3 text-sm font-bold text-emerald-800">
                  <span>Total:</span>
                  <span className="font-mono tabular-nums">{formatINR(s.eligibleTotal)}</span>
                </div>
              </div>
              <div className="mt-auto border-l-4 border-l-emerald-600 bg-[#F0FDF4] p-3 text-xs text-emerald-900/90">
                Eligible B2B ITC from matched invoices (ITC available = Y).
              </div>
            </div>

            <div className="flex flex-col rounded-lg border border-border">
              <div className="space-y-2 border-b border-border p-4">
                <p className="text-[13px] font-semibold text-red-700">✗ Do NOT Claim (Table 4D(1))</p>
                {s.ineligibleTotal === 0 ? (
                  <p className="text-sm font-medium text-emerald-700">{formatINR(0)} — All ITC eligible</p>
                ) : (
                  <>
                    <MoneyRow label="IGST:" value={s.ineligibleIGST} />
                    <MoneyRow label="CGST:" value={s.ineligibleCGST} />
                    <MoneyRow label="SGST:" value={s.ineligibleSGST} />
                    <div className="my-2 border-t border-border" />
                    <div className="flex justify-between gap-3 text-sm font-bold text-red-800">
                      <span>Total:</span>
                      <span className="font-mono tabular-nums">{formatINR(s.ineligibleTotal)}</span>
                    </div>
                  </>
                )}
              </div>
              <div className="mt-auto border-l-4 border-l-red-600 bg-[#FEF2F2] p-3 text-xs text-red-900/90">
                Section 17(5) / blocked ITC per GSTR-2B (ITC available = N).
              </div>
            </div>

            <div className="flex flex-col rounded-lg border border-border">
              <div className="space-y-2 border-b border-border p-4">
                <p className="text-[13px] font-semibold text-amber-800">⏸ Deferred (claim next month)</p>
                <div className="flex justify-between gap-3 text-sm">
                  <span className="text-muted-foreground">Missing in 2B:</span>
                  <span className="font-mono tabular-nums font-medium text-orange-700">
                    {formatINR(s.deferredTotal)}
                  </span>
                </div>
                <div className="flex justify-between gap-3 text-sm">
                  <span className="text-muted-foreground">QRMP pending:</span>
                  <span className="font-mono tabular-nums font-medium text-blue-700">
                    {formatINR(s.qrmpTotal)}
                  </span>
                </div>
                <div className="my-2 border-t border-border" />
                <div className="flex justify-between gap-3 text-sm font-bold text-amber-900">
                  <span>Total deferred:</span>
                  <span className="font-mono tabular-nums">{formatINR(totalDeferred)}</span>
                </div>
              </div>
              <div className="mt-auto border-l-4 border-l-amber-500 bg-[#FFFBEB] p-3 text-xs text-amber-950/90">
                PR-only (not expired) and QRMP invoices — do not enter in this month&apos;s 4A(5).
              </div>
            </div>
          </div>

          <div className="mt-4 flex flex-col rounded-lg border border-border bg-white shadow-sm">
            <div className="space-y-2 border-b border-border p-4">
              <p className="text-[13px] font-semibold text-brand-navy">Credit / Debit Notes</p>
              <div className="flex justify-between gap-3 text-sm">
                <span className="text-muted-foreground">Credit Notes ITC</span>
                <span className="font-mono tabular-nums font-medium text-red-600">
                  {formatINR(s.creditNoteITC ?? 0)}
                </span>
              </div>
              <div className="flex justify-between gap-3 text-sm">
                <span className="text-muted-foreground">Debit Notes ITC</span>
                <span className="font-mono tabular-nums font-medium text-emerald-700">
                  {formatINR(s.debitNoteITC ?? 0)}
                </span>
              </div>
              <div className="my-2 border-t border-border" />
              <div className="flex justify-between gap-3 text-sm font-semibold text-brand-navy">
                <span>Net adjustment</span>
                <span className="font-mono tabular-nums">
                  {formatINR((s.creditNoteITC ?? 0) + (s.debitNoteITC ?? 0))}
                </span>
              </div>
            </div>
            <div className="border-l-4 border-l-slate-400 bg-slate-50 p-3 text-xs text-slate-800/90">
              Matched, ITC-available credit and debit notes from GSTR-2B (Table 4A adjustments).
            </div>
          </div>

          <div className="mt-6 rounded-lg border border-blue-100 bg-[#EFF6FF] px-4 py-4 sm:px-5">
            <p className="text-base font-bold text-brand-navy sm:text-lg">
              Net ITC to enter in GSTR-3B Table 4A(5): {formatINR(s.netAfterNotes ?? s.netClaimableTotal)}
            </p>
            <div className="mt-2 space-y-1 text-xs text-muted-foreground md:mt-1 md:flex md:flex-row md:flex-wrap md:gap-x-4 md:space-y-0 md:text-sm">
              <p>IGST: {formatINR(s.netClaimableIGST)}</p>
              <p>CGST: {formatINR(s.netClaimableCGST)}</p>
              <p>SGST: {formatINR(s.netClaimableSGST)}</p>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}
